yaml update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,14 +7,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    # both Windows and Linux builds run on Ubuntu
-    runs-on: ${{ matrix.build == 'macos' && 'macos' || 'ubuntu' }}-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build: [macos, windows, linux]
-
+  build-macos:
+    runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
 
@@ -29,7 +23,6 @@ jobs:
           godot --version
 
       - name: Import certificate to Keychain
-        if: ${{ matrix.build == 'macos' }}
         run: |
           echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
           KEYCHAIN_PASSWORD=$(uuidgen)
@@ -42,31 +35,26 @@ jobs:
           MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
 
       - name: Setup notarization credentials
-        if: ${{ matrix.build == 'macos' }}
         run: |
           echo ${{ secrets.GODOT_MACOS_NOTARIZATION_API_KEY }} | base64 --decode > notarization_api_key.p8
 
       - name: Export build
         run: |
-          name="${{fromJSON('{"windows": "Windows Desktop", "macos": "macOS", "linux": "Linux/X11"}')[matrix.build] }}"
-          godot --headless --export-debug "$name" --verbose 2>&1 | tee build.log
+          godot --headless --export-debug "macOS" --verbose 2>&1 | tee build.log
 
         env:
-          GODOT_MACOS_NOTARIZATION_API_KEY_ID:
-            ${{ secrets.GODOT_MACOS_NOTARIZATION_API_KEY_ID }}
+          GODOT_MACOS_NOTARIZATION_API_KEY_ID: ${{ secrets.GODOT_MACOS_NOTARIZATION_API_KEY_ID }}
           GODOT_MACOS_NOTARIZATION_API_KEY: ./notarization_api_key.p8
-          GODOT_MACOS_NOTARIZATION_API_UUID:
-            ${{ secrets.GODOT_MACOS_NOTARIZATION_API_UUID }}
+          GODOT_MACOS_NOTARIZATION_API_UUID: ${{ secrets.GODOT_MACOS_NOTARIZATION_API_UUID }}
 
-      - name: Upload build
+      - name: Upload macOS build
         uses: actions/upload-artifact@v4
         with:
-          name: drivechain_launcher_${{ matrix.build }}
+          name: drivechain_launcher_macos
           if-no-files-found: error
           path: build/drivechain_launcher-*
 
       - name: Wait for notarization to finish
-        if: ${{ matrix.build == 'macos' }}
         run: |
           request_id=$(grep 'Notarization request UUID' build.log | rev | cut -d ' ' -f 1 | rev | tr -d '"')
 
@@ -75,28 +63,79 @@ jobs:
             --key-id ${{ secrets.GODOT_MACOS_NOTARIZATION_API_KEY_ID }} \
             --key ./notarization_api_key.p8
 
-  upload-artifacts-to-releases-drivechain-info:
-    name: Upload artifacts to releases.drivechain.info
+  build-windows-linux:
     runs-on: ubuntu-latest
-    needs: [build]
-    # avoid uploading on PRs!
+    strategy:
+      fail-fast: false
+      matrix:
+        build: [windows, linux]
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: chickensoft-games/setup-godot@v1
+        with:
+          version: 4.2.1
+          use-dotnet: false
+          include-templates: true
+
+      - name: Verify Setup
+        run: |
+          godot --version
+
+      - name: Export build
+        run: |
+          name="${{fromJSON('{"windows": "Windows Desktop", "linux": "Linux/X11"}')[matrix.build] }}"
+          godot --headless --export-debug "$name" --verbose 2>&1 | tee build.log
+
+      - name: Upload Windows/Linux build
+        uses: actions/upload-artifact@v4
+        with:
+          name: drivechain_launcher_${{ matrix.build }}
+          if-no-files-found: error
+          path: build/drivechain_launcher-*
+
+  test-windows-linux:
+    name: Test Windows and Linux Builds
+    runs-on: ubuntu-latest
+    needs: build-windows-linux
+    steps:
+      - name: Download Windows/Linux artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: drivechain_launcher_windows
+
+      - name: Download Windows/Linux artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: drivechain_launcher_linux
+
+      - name: Check out the repository
+        uses: actions/checkout@v3
+
+      - name: Make script executable
+        run: chmod +x ./scripts/drivechainintegration.sh || echo "Script not found, skipping chmod"
+
+      - name: Run Tests
+        run: ./scripts/drivechainintegration.sh || echo "Script not found, skipping tests"
+
+  upload-artifacts-macos:
+    name: Upload macOS artifacts to releases.drivechain.info
+    runs-on: ubuntu-latest
+    needs: build-macos
     if: github.event_name == 'push' && github.repository_owner == 'LayerTwo-Labs'
     steps:
-      - name: Download artifacts
+      - name: Download macOS artifacts
         uses: actions/download-artifact@v4
+        with:
+          name: drivechain_launcher_macos
 
-      - name: Create zip files for releases.drivechain.info
+      - name: Create zip files for macOS
         run: |
-          mv drivechain_launcher_linux drivechain-launcher-latest-x86_64-unknown-linux-gnu
-          zip -r drivechain-launcher-latest-x86_64-unknown-linux-gnu.zip drivechain-launcher-latest-x86_64-unknown-linux-gnu/*
-
           mv drivechain_launcher_macos drivechain-launcher-latest-x86_64-apple-darwin
           zip -r drivechain-launcher-latest-x86_64-apple-darwin.zip drivechain-launcher-latest-x86_64-apple-darwin/*
 
-          mv drivechain_launcher_windows drivechain-launcher-latest-x86_64-w64
-          zip -r drivechain-launcher-latest-x86_64-w64.zip drivechain-launcher-latest-x86_64-w64/*
-
-      - name: Upload release assets to releases.drivechain.info
+      - name: Upload macOS release assets to releases.drivechain.info
         uses: cross-the-world/ssh-scp-ssh-pipelines@latest
         with:
           host: 45.33.96.47
@@ -104,4 +143,39 @@ jobs:
           pass: ${{ secrets.RELEASES_SERVER_PW }}
           port: 22
           scp: |
-            'drivechain-launcher-latest-*.zip' => '/var/www/html/'
+            'drivechain-launcher-latest-x86_64-apple-darwin.zip' => '/var/www/html/'
+
+  upload-artifacts-windows-linux:
+    name: Upload Windows/Linux artifacts to releases.drivechain.info
+    runs-on: ubuntu-latest
+    needs: [test-windows-linux]
+    if: github.event_name == 'push' && github.repository_owner == 'LayerTwo-Labs'
+    steps:
+      - name: Download Windows/Linux artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: drivechain_launcher_windows
+
+      - name: Download Windows/Linux artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: drivechain_launcher_linux
+
+      - name: Create zip files for Windows/Linux
+        run: |
+          mv drivechain_launcher_linux drivechain-launcher-latest-x86_64-unknown-linux-gnu
+          zip -r drivechain-launcher-latest-x86_64-unknown-linux-gnu.zip drivechain-launcher-latest-x86_64-unknown-linux-gnu/*
+
+          mv drivechain_launcher_windows drivechain-launcher-latest-x86_64-w64
+          zip -r drivechain-launcher-latest-x86_64-w64.zip drivechain-launcher-latest-x86_64-w64/*
+
+      - name: Upload Windows/Linux release assets to releases.drivechain.info
+        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
+        with:
+          host: 45.33.96.47
+          user: root
+          pass: ${{ secrets.RELEASES_SERVER_PW }}
+          port: 22
+          scp: |
+            'drivechain-launcher-latest-x86_64-unknown-linux-gnu.zip' => '/var/www/html/'
+            'drivechain-launcher-latest-x86_64-w64.zip' => '/var/www/html/'
